Section A: Data Structures & Control Structures

1.	Create a list of 5 integers. Perform and print the result of the following operations: append, extend, insert, remove, pop, clear, index, count, sort, and reverse.

In [20]:
list_1 = [1,2,3,4,5]

In [21]:
#Append
list_1.append(7)
list_1

[1, 2, 3, 4, 5, 7]

In [23]:
#extend
list_2 = [33,45]
list_1.extend(list_2)
list_1

[1, 2, 3, 4, 5, 7, 33, 45, 33, 45]

In [25]:
#insert
list_1.insert(2,89)
list_1

[1, 2, 89, 3, 4, 5, 7, 33, 45, 33, 45]

In [26]:
#remove
list_1.remove(33)
list_1

[1, 2, 89, 3, 4, 5, 7, 45, 33, 45]

In [29]:
#pop
list_1.pop()
list_1

[1, 2, 89, 3, 4, 5, 7]

In [31]:
#clear
list_1.clear()
list_1

[]

In [37]:
#index
list_1 = [7,5,8,9,10]
index =list_1.index(8)
index

2

In [42]:
#count
list_1.count(9)

1

In [46]:
#sort
list_1.sort()
list_1

[5, 7, 8, 9, 10]

In [47]:
list_1.reverse()
list_1

[10, 9, 8, 7, 5]

2.	Create a tuple that stores 3 student names. Try changing the second name in the tuple. What happens? Explain why.

In [49]:
#Tuple
students = ("Pranav","Sumedh","Vedant")
students

('Pranav', 'Sumedh', 'Vedant')

In [54]:
students[1] = "Pavan"
students

TypeError: 'tuple' object does not support item assignment

Explanation:
- Tuples are immutable in Python.
- That means once a tuple is created, you cannot change, add, or remove elements directly.
- Trying to modify any element will result in a TypeError.

3.	Create a set of integers with some duplicate values. Print the set and explain the output.

In [56]:
set_1 = {10,12,15,10,45,12,58,15,45}
set_1

{10, 12, 15, 45, 58}

Explanation:
- The set removes all duplicate values automatically
- It keeps only unique elements: {10, 12, 15, 45, 58}
- The order of elements may vary because sets are unordered collections.

4.	Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary.

In [58]:
# Creating the dictionary
person = {'name': 'Sumedh', 'age': 22, 'city': 'Pune'}
person

{'name': 'Sumedh', 'age': 22, 'city': 'Pune'}

In [59]:
# Updating the age
person['age'] = 23
person

{'name': 'Sumedh', 'age': 23, 'city': 'Pune'}

In [60]:
# Adding a new key 'email'
person['email'] = 'sumedhjoshi2373@gmail.com'
person

{'name': 'Sumedh',
 'age': 23,
 'city': 'Pune',
 'email': 'sumedhjoshi2373@gmail.com'}

5.	 Write a script that checks if a person is eligible to vote (age ≥ 18). Take age as a variable and print the appropriate message.

In [61]:

age = int(input("Enter your age: "))

if age >= 18:
    print("You are eligible to vote.")
else:
    print("You are not eligible to vote yet.")


Enter your age: 22
You are eligible to vote.


6.	Given a 'marks' variable, print the grade:
- 90 and above: 'A'
- 75–89: 'B'
- 50–74: 'C'
- Below 50: 'Fail'


In [63]:
marks = int(input("Enter your marks: "))

if marks >= 90:
    print("Grade: A")
elif marks >= 75:
    print("Grade: B")
elif marks >= 50:
    print("Grade: C")
else:
    print("Grade: Fail")


Enter your marks: 95
Grade: A


7.	Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative

In [64]:
num = int(input("Enter a number: "))

if num > 0:
    if num % 2 == 0:
        print("The number is positive and even.")
    else:
        print("The number is positive but odd.")
elif num == 0:
    print("The number is zero.")
else:
    print("The number is negative.")


Enter a number: 59
The number is positive but odd.


Section B: Numpy

8.	Create:
- A scalar using np.array(5)
- A 1D array with values 1 to 5
- A 2D array (2x3) with values from 10 to 60 in steps of 10


In [65]:
import numpy as np

In [68]:
#A scalar using np.array(5)
scalar = np.array(5)
print("Scalar:", scalar)

Scalar: 5


In [71]:
#A 1D array with values 1 to 5
array_1d = np.array([1, 2, 3, 4, 5])
array_1d

array([1, 2, 3, 4, 5])

In [72]:
#A 2D array (2x3) with values from 10 to 60 in steps of 10
array_2d = np.array([[10, 20, 30], [40, 50, 60]])
array_2d

array([[10, 20, 30],
       [40, 50, 60]])

9.	Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().

In [73]:
random_array = np.random.randint(0, 101, size=(4, 4))
random_array

array([[24, 12, 49, 52],
       [78, 40, 79, 37],
       [20, 37,  4, 12],
       [68, 42, 67, 38]])

10.	Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.

In [74]:
import numpy as np
import pandas as pd


In [75]:
array_2d = np.array([[10, 15, 30],
                     [98, 50, 67],
                     [74,59, 9]])

In [77]:
df = pd.DataFrame(array_2d, columns=['A', 'B', 'C'])
df                  

,A,B,C
0,10,15,30
1,98,50,67
2,74,59,9


Section C: Exploring Pandas

11.	Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then:
- Use .info(), .describe()
- Select 'Name' and 'City' columns
- Drop 'City' column
- Fill any missing values in 'Salary' column with the mean
- Remove any duplicate rows


In [81]:
data = {
    'Name': ['Sumedh', 'pranav', 'Ananya', 'Sukhada', 'vedant', 'pavan', 'Atharva', 'Vikram', 'varad', 'yash'],
    'Age': [25, 30, 22, 28, 25, 35, 27, 40, 32, 22],
    'City': ['Pune', 'Mumbai', 'Delhi', 'Pune', 'Pune', 'Bangalore', 'Mumbai', 'Delhi', 'Chennai', 'Delhi'],
    'Salary': [50000, 60000, np.nan, 55000, 50000, 65000, np.nan, 70000, 62000, 55000]
}

In [82]:
df = pd.DataFrame(data)

In [84]:
#.info
print("DataFrame Info:")
print(df.info(),)

DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     object 
 1   Age     10 non-null     int64  
 2   City    10 non-null     object 
 3   Salary  8 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes
None 



In [87]:
#.describe
print("DataFrame Description:")
print(df.describe())

DataFrame Description:
            Age        Salary
count  10.00000      8.000000
mean   28.60000  58375.000000
std     5.77735   7150.174823
min    22.00000  50000.000000
25%    25.00000  53750.000000
50%    27.50000  57500.000000
75%    31.50000  62750.000000
max    40.00000  70000.000000


In [88]:
#Select 'Name' and 'City' columns
print("🔹 Selected Columns (Name & City):")
print(df[['Name', 'City']])

🔹 Selected Columns (Name & City):
      Name       City
0   Sumedh       Pune
1   pranav     Mumbai
2   Ananya      Delhi
3  Sukhada       Pune
4   vedant       Pune
5    pavan  Bangalore
6  Atharva     Mumbai
7   Vikram      Delhi
8    varad    Chennai
9     yash      Delhi


In [89]:
#Drop 'City' column
df = df.drop(columns=['City'])
print("After Dropping 'City' Column:")
print(df)

After Dropping 'City' Column:
      Name  Age   Salary
0   Sumedh   25  50000.0
1   pranav   30  60000.0
2   Ananya   22      NaN
3  Sukhada   28  55000.0
4   vedant   25  50000.0
5    pavan   35  65000.0
6  Atharva   27      NaN
7   Vikram   40  70000.0
8    varad   32  62000.0
9     yash   22  55000.0


In [90]:
#Fill any missing values in 'Salary' column with the mean
df['Salary'].fillna(df['Salary'].mean(), inplace=True)
print("After Filling Missing Salary Values:")
print(df)

After Filling Missing Salary Values:
      Name  Age   Salary
0   Sumedh   25  50000.0
1   pranav   30  60000.0
2   Ananya   22  58375.0
3  Sukhada   28  55000.0
4   vedant   25  50000.0
5    pavan   35  65000.0
6  Atharva   27  58375.0
7   Vikram   40  70000.0
8    varad   32  62000.0
9     yash   22  55000.0


In [91]:
#Remove any duplicate rows
df = df.drop_duplicates()
print("After Removing Duplicates:")
print(df)

After Removing Duplicates:
      Name  Age   Salary
0   Sumedh   25  50000.0
1   pranav   30  60000.0
2   Ananya   22  58375.0
3  Sukhada   28  55000.0
4   vedant   25  50000.0
5    pavan   35  65000.0
6  Atharva   27  58375.0
7   Vikram   40  70000.0
8    varad   32  62000.0
9     yash   22  55000.0
